const map=L.map('map',{zoomControl:true}).setView([40.7128,-74.0060],11);
const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const imagery=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'Esri, Maxar, Earthstar Geographics'});
L.control.layers({'Street':street,'Aerial':imagery},{},{position:'topright'}).addTo(map);L.control.scale({imperial:true,metric:false}).addTo(map);
const $=id=>document.getElementById(id);let searchMarker;
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function val(p,...keys){for(const k of keys)if(p[k]!==undefined&&p[k]!==null&&String(p[k]).trim()!=='')return p[k];return '';}
function districts(p){return ['ZoneDist1','ZoneDist2','ZoneDist3','ZoneDist4'].map(k=>val(p,k,k.toLowerCase())).filter(Boolean).join(', ');}
function overlays(p){return ['Overlay1','Overlay2'].map(k=>val(p,k,k.toLowerCase())).filter(Boolean).join(', ');}
function specials(p){return ['SPDist1','SPDist2','SPDist3'].map(k=>val(p,k,k.toLowerCase())).filter(Boolean).join(', ');}
function showSelected(title,rows){$('selectedInfo').innerHTML=`<div class="result-title">${esc(title)}</div>`+rows.filter(Boolean).map(r=>`<div class="result-row">${r}</div>`).join('');}
function zoningRows(p){const z=districts(p),o=overlays(p),s=specials(p);return [z?`<strong>Zoning district${z.includes(',')?'s':''}: ${esc(z)}</strong>`:'Zoning district: not populated',o?`Commercial overlay: <strong>${esc(o)}</strong>`:'',s?`Special district: <strong>${esc(s)}</strong>`:'',val(p,'LtdHeight','ltdheight')?`Limited height district: ${esc(val(p,'LtdHeight','ltdheight'))}`:'',val(p,'SplitZone','splitzone')?`Split zoning: ${esc(val(p,'SplitZone','splitzone'))}`:''];}
const MAPPLUTO_URL='https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/MAPPLUTO/FeatureServer/0';
const lots=L.esri.featureLayer({url:MAPPLUTO_URL,simplifyFactor:.35,precision:5,minZoom:15,style:f=>{const z=String(val(f.properties||{},'ZoneDist1','zonedist1'));let fill='#3388cc';if(z.startsWith('R'))fill='#d6a84b';else if(z.startsWith('C'))fill='#d86b6b';else if(z.startsWith('M'))fill='#8b75b8';return{color:'#1468a8',weight:1,fillColor:fill,fillOpacity:.16};}}).addTo(map);
lots.bindPopup(layer=>{const p=layer.feature?.properties||{},z=districts(p);return `<strong>${esc(val(p,'Address','address')||'NYC Tax Lot')}</strong><br>BBL: ${esc(val(p,'BBL','bbl'))}<br><strong>Zoning: ${esc(z||'not populated')}</strong><br><small>NYC DCP MapPLUTO</small>`;});
lots.on('click',e=>{const p=e.layer.feature?.properties||{};showSelected(val(p,'Address','address')||'NYC Tax Lot',[`BBL: <strong>${esc(val(p,'BBL','bbl'))}</strong>`,`Block: ${esc(val(p,'Block','block'))} &nbsp; Lot: ${esc(val(p,'Lot','lot'))}`,...zoningRows(p),val(p,'LotArea','lotarea')?`Lot area: ${Number(val(p,'LotArea','lotarea')).toLocaleString()} sf`:'',val(p,'BldgArea','bldgarea')?`Building area: ${Number(val(p,'BldgArea','bldgarea')).toLocaleString()} sf`:'',val(p,'LandUse','landuse')?`Land use code: ${esc(val(p,'LandUse','landuse'))}`:'','Source: <strong>NYC DCP MapPLUTO</strong>']);});
async function geosearch(q){const r=await fetch(`https://geosearch.planninglabs.nyc/v2/search?text=${encodeURIComponent(q)}`);if(!r.ok)throw new Error('NYC address search is unavailable.');return (await r.json()).features?.[0];}
$('searchForm').addEventListener('submit',async e=>{e.preventDefault();const q=$('searchInput').value.trim();if(!q)return;try{const f=await geosearch(q);if(!f)throw new Error('No NYC location found.');const[lng,lat]=f.geometry.coordinates;map.setView([lat,lng],18);if(searchMarker)map.removeLayer(searchMarker);searchMarker=L.marker([lat,lng]).addTo(map);const p=f.properties||{},label=p.label||p.name||q;searchMarker.bindPopup(`<strong>${esc(label)}</strong><br>Click the highlighted tax lot for zoning details.`).openPopup();showSelected(label,[p.borough?`Borough: <strong>${esc(p.borough)}</strong>`:'',p.postalcode?`ZIP: ${esc(p.postalcode)}`:'',p.addendum?.pad?.bbl?`BBL: <strong>${esc(p.addendum.pad.bbl)}</strong>`:'','Click the tax lot for zoning districts, overlays and special districts.']);}catch(err){showSelected('Search error',[esc(err.message)]);}});
$('toggleLots').addEventListener('change',e=>e.target.checked?lots.addTo(map):map.removeLayer(lots));